language: ruby

os: linux
dist: bionic

deploy:
  fqdn: gbigrogol.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

script: bundle exec jekyll build

after_success:
 - chmod 777 deploy.sh
 - ./deploy.sh